export const CHECK_NODE_STATUS_START = 'CHECK_NODE_STATUS_START';
export const CHECK_NODE_STATUS_SUCCESS = 'CHECK_NODE_STATUS_SUCCESS';
export const CHECK_NODE_STATUS_FAILURE = 'CHECK_NODE_STATUS_FAILURE';

export const CHECK_NODE_BLOCK_START = 'CHECK_NODE_BLOCK_START';
export const CHECK_NODE_BLOCK_SUCCESS = 'CHECK_NODE_BLOCK_SUCCESS';
export const CHECK_NODE_BLOCK_FAILURE = 'CHECK_NODE_BLOCK_FAILURE';
